use_frameworks!

target 'RCEmojiKit_Example' do
  pod 'RCEmojiKit', :path => '../'

  target 'RCEmojiKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.3'
  end
end
